---
- name: configure ntp and acl via CLI
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: set ACL via CLI
    cisco.ios.ios_config:
      lines:
        - 30 permit ip host 3.3.3.3 any log
        - 40 permit ip host 4.4.4.4 any log
        - 50 permit ip host 5.5.5.5 any log
      parents: ['ip access-list extended my_acl']


  - name: set ntp server 10.1.{{subnet_id}}.{{item}} via CLI
    cisco.ios.ios_config:
      lines:
        - ntp server 10.1.{{subnet_id}}.{{item}}
    loop:
        - 11
        - 12
        - 13
        - 14